# Generated by Django 3.1.3 on 2020-12-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpg', models.IntegerField()),
                ('cylinders', models.IntegerField()),
                ('displacement', models.IntegerField()),
                ('horsepower', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('acceleration', models.IntegerField()),
                ('model_year', models.IntegerField()),
                ('origin', models.IntegerField()),
                ('car_name', models.CharField(max_length=100)),
            ],
        ),
    ]
